name = "RoughSurface"
uuid = "62d47e0b-a6c6-459b-bc05-79960055e5a2"
authors = ["nil-is-lin"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Documenter = "0.25"
FileIO = "1.4"
JLD2 = "0.1"
PyCall = "1.91"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
